### ISSUE TITLE
Problem updating and preCompiling PyRhodium

### ISSUE THREAD

**Issue by sdt2** [davidanthoff/PyRhodium.jl#10]
Hi David, 

I attempted to update PyRhodium via the Julia PowerShell but am getting errors when I attempt to pre-compile and use the new version. I am using Julia version 1.1.0 on a Windows machine. The steps I've taken and the errors I'm receiving are described below - my code is in bold.

_Step 1: Update PyRhodium_
**(v1.1) pkg> update**
  Updating registry at `C:\Users\sturner\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/davidanthoff/PyRhodium.jl.git`
 Resolving package versions...
ERROR: path C:\Users\sturner\.julia\packages\PyRhodium\pIdWI for package PyRhodium no longer exists. Remove the package or `develop` it at a new path

_Step 2: Follow Instructions to remove PyRhodium and re-add_ 
**julia> Remove PyRhodium 
julia> Add PyRhodium**

_Step 3: Attempt to use PyRhodium_
**julia> using PyRhodium**
[ Info: Precompiling PyRhodium [e525b322-f4d5-5e8a-9e4c-f31b6ef474ca]
Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x6e05bf91 -- PyType_IsSubtype at C:\Users\sturner\.julia\conda\3\python36.dll (unknown line)
in expression starting at C:\Users\sturner\.julia\packages\PyRhodium\aU37D\src\PyRhodium.jl:4
PyType_IsSubtype at C:\Users\sturner\.julia\conda\3\python36.dll (unknown line)
Allocations: 8837946 (Pool: 8836581; Big: 1365); GC: 18
ERROR: Failed to precompile PyRhodium [e525b322-f4d5-5e8a-9e4c-f31b6ef474ca] to C:\Users\sturner\.julia\compiled\v1.1\PyRhodium\8T2pg.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1197
 [3] _require(::Base.PkgId) at .\loading.jl:960
 [4] require(::Base.PkgId) at .\loading.jl:858
 [5] require(::Module, ::Symbol) at .\loading.jl:853

Any suggestions you might have would be much appreciated. If more info is desirable let me know. 

Thanks, 
Sara

**Comment by davidanthoff** [comment]
Hm, very weird... Can you try the following:

1. At the pkg REPL, enter `up`.
2. At the pkg REPL, enter `status` and paste the output of that here for us to see.
3. Try to run `build` at the pkg REPL, and see whether that fixes it.

**Comment by sdt2** [comment]
Thanks, I was able to get PyRhodium working again.
